services:
  # Backend API
  - type: web
    name: ev-charging-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ev-charging-db
          property: connectionString

  # Frontend React App
  - type: web
    name: ev-charging-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: ev-charging-backend
          property: host

databases:
  # PostgreSQL Database
  - name: ev-charging-db